### ISSUE TITLE
关于对比算法

### ISSUE THREAD

**Issue by zlx913** [heiyuxiaokai/focal-teacher#1]
感谢您出色的工作！我想问一下您论文中对比算法DDPLS的结果是怎么跑的，因为在DDPLS论文中publish出来有55.6，是因为实验设置的问题吗，还是数据增强不同的原因，期待您的回复！

**Comment by heiyuxiaokai** [comment]
@zlx913 ddpls论文中的精度有两种版本，分别为使用了scale jittering和不使用scale jittering。参照了SOOD的工作，我们在对比试验中主要引用了该论文中不使用scale jittering的实验结果。

**Comment by zlx913** [comment]
我看到ddpls论文中的表三了，感谢！
